refactor: model operation in BatchCommand model
WikiMovimentoBrasil/quickstatements3 pull request #130
Opened 2024-12-02 13:40 UTC by arcstur

The operation related to the command is now modeled in BatchCommand (not completed yet).

We have create item, create property, remove statement by id, remove statement by value, set sitelink and remove sitelink (and updated the parser for that). This ensures better operationability with the API logic.

Also, set possible errors in the model as well, still not shown in the UI.11

2024-12-04 11:50 UTC, mgalves requested changes

2024-12-04 20:39 UTC, arcstur commented on src/core/models.py
> -        if preview_command is not None and type(preview_command) == BatchCommand:
beleza! sim, saudades mesmo kkkkkkkk

2024-12-04 20:40 UTC, arcstur commented on src/core/client.py
>          if method == "POST":
tem razão, vou refatorar

2024-12-09 19:09 UTC, mgalves approved these changes

2024-12-09 19:09 UTC, merged