fix: fixes and improvements
WikiMovimentoBrasil/quickstatements3 pull request #133
Opened 2024-12-28 22:32 UTC by arcstur

2024-12-31 21:21 UTC, mgalves requested changes

2024-12-31 21:21 UTC, mgalves commented on src/web/templates/batch.html
> +      hx-trigger="load, every 3s"
3s não é muito rapido?

2024-12-31 21:21 UTC, mgalves commented on src/web/templates/batches.html
> +        <a href="{{base_url}}?page={{page.next_page_number}}">
não entendi aqui qual era o problema com o {% url 'last_batches_by_user' user=user %}

2024-12-31 22:31 UTC, arcstur commented on src/web/templates/batch.html
> +      hx-trigger="load, every 3s"
talvez, mas 10s é muito lento kkkkk; e olha, vai ser só pra lotes em INITIAL ou RUNNING, então talvez dê pra usar... pelo que eu testei aqui, o servidor consegue responder esse request bem rápido (<50ms)

2024-12-31 22:32 UTC, arcstur commented on src/web/templates/batches.html
> +        <a href="{{base_url}}?page={{page.next_page_number}}">
eu fiz isso pra poder reutilizar o 'batches.html' tanto com o batches by user quanto com o last batches (todos usuários), no by user ele passa a base_url pra usar by user, e no geral ele usa base_url pra usar o geral

2025-01-02 19:51 UTC, mgalves approved these changes

2025-01-02 19:51 UTC, merged